package com.saja.mytask.network.models

data class FawateercomBillPaymentResponse (
    val a2AChannel: String? = null,
    val a2APWD: String? = null,
    val a2AUserID: String? = null,
    val accessChannel: String? = null,
    val address: String? = null,
    val billerCode: String? = null,
    val billingNo: String? = null,
    val billNo: String? = null,
    val currency: String? = null,
    val custID: String? = null,
    val custInfoFlag: String? = null,
    val dueAmt: String? = null,
    val eMail: String? = null,
    val errorCode: String? = null,
    val errorEDesc: String? = null,
    val fees: String? = null,
    val id: String? = null,
    val idType: String? = null,
    val inqRefNo: String? = null,
    val joebppsNo: String? = null,
    val joebppsTrx: String? = null,
    val mobileNo: String? = null,
    val msgLang: String? = null,
    val name: String? = null,
    val nation: String? = null,
    val paidAmt: String? = null,
    val paymentMethod: String? = null,
    val phone: String? = null,
    val pmtStatus: String? = null,
    val sendSMSFlag: String? = null,
    val serviceType: String? = null,
    val trxRefNo: String? = null
)