package com.saja.mytask.network.models

data class FawateercomPrePaidValidationResponse (
    val a2AChannel: String? = null,
    val a2APWD: String? = null,
    val a2AUserID: String? = null,
    val address: String? = null,
    val benAName: String? = null,
    val benEName: String? = null,
    val benNation: String? = null,
    val billerCode: String? = null,
    val billingNo: String? = null,
    val custID: String? = null,
    val custInfoFlag: String? = null,
    val custName: String? = null,
    val denomination: String? = null,
    val dueAmt: String? = null,
    val eMail: String? = null,
    val errorCode: String? = null,
    val errorEDesc: String? = null,
    val fees: String? = null,
    val freeText: String? = null,
    val id: String? = null,
    val idType: String? = null,
    val name: String? = null,
    val nation: String? = null,
    val phone: String? = null,
    val receivingCountry: String? = null,
    val senderAName: String? = null,
    val senderEName: String? = null,
    val senderID: String? = null,
    val senderIDType: String? = null,
    val senderNation: String? = null,
    val serviceType: String? = null,
    val transferReason: String? = null,
    val validationCode: String? = null
)
